### ISSUE TITLE
[bug][duplicate] Remove PIVX Purple color from QT

### ISSUE THREAD

**Issue by bradinator** [ioncoincore/ion-v4#59] opened 2019-01-24 14:03 UTC
**Is your feature request related to a problem? Please describe.**
Current builds of QT still have many of the purple colors from original PIVX fork. 
The Main color of sidebar especially should be change.  In qt CSS, there are many uses of #3a235e which is the purple color.

**Describe the solution you'd like**
Ideally, colors matching closer with current ION/ionomy style guides, and move away from main purple color of pivx

**Describe alternatives you've considered**
Other color options would be ok.  A very basic black & white setup would be functional.

**Comment by cevap** [comment] 2019-01-24 17:24
this duplicate, issues was raised on old repo. this issue is duplicate of: https://github.com/ioncoincore/ion/issues/11

I will close it for better overview due to being duplicate, feel free to reopen if there is a need for that.

**Closed as completed by cevap** 2019-01-24 17:24 UTC
Labels: Bug, duplicate
