### ISSUE TITLE
[Bug][Windows][Wallet Sync]ION Daemon and Qt clients stop syncing

### ISSUE THREAD

**Issue by krumblez** [ioncoincore/ion-v4#134] opened 2019-03-08 17:23 UTC
**Passed on from ION Jord**

**Describe the bug**

**Both IOND and Qt instances**

"I am now seeing a large amount of issues with syncing on this wallet,
The wallet gets to a certain point and stops, only a delete of the blockchain works"

**To Reproduce**
Install client, sync, leave for some time.

**Expected behaviour**
Continue to sync normally and not stop as has been doing.

**Console Data**

2019-03-07 20:15:12 ERROR: AcceptBlock : prev block 9391760af8fe350dae9b09d7145aa067a793a3cb473ba336c5d8a4af0b8cdbe2 is invalid, unable to add block db967a28602b79074e156b7c39534ba946685a5681b79c6462bda454ae700bca

2019-03-07 20:15:12 ERROR: ProcessNewBlock : AcceptBlock FAILED

"This is some of the errors I'm seeing in the wallet
For example, I've just restarted a fresh wallet, added my blockchain and it's about 20 blocks out from being up to date
The wallet has 16 connections but it's not downloading the latest blocks
This wallet is stuck on block 1044699
I took the blockchain from a working syncing wallet
But it's still not working
A bit more debug code to help the devs"

2019-03-07 20:18:00 ERROR: ProcessNewBlock : AcceptBlock FAILED
2019-03-07 20:18:00 Misbehaving: 45.76.236.45:12700 (0 -> 100) BAN THRESHOLD EXCEEDED
2019-03-07 20:18:00 connect() to 157.230.210.220:12700 failed after select(): Connection refused (111)
2019-03-07 20:18:00 ERROR: AcceptBlock : prev block 9391760af8fe350dae9b09d7145aa067a793a3cb473ba336c5d8a4af0b8cdbe2 is invalid, unable to add block db967a28602b79074e156b7c39534ba946685a5681b79c6462bda454ae700bca
2019-03-07 20:18:00 ERROR: ProcessNewBlock : AcceptBlock FAILED
2019-03-07 20:18:00 Misbehaving: 45.32.217.224:12700 (0 -> 100) BAN THRESHOLD EXCEEDED
2019-03-07 20:18:01 connect() to 46.101.11.125:12700 failed after select(): Connection refused (111)
2019-03-07 20:18:02 receive version message: /Helium:3.1.1/: version 95702, blocks=1044733, us=95.216.166.5:39692, peer=158
2019-03-07 20:18:02 Added time data, samples 147, offset +0 (+0 minutes)
2019-03-07 20:18:02 nTimeOffset = +0  (+0 minutes)
2019-03-07 20:18:03 ERROR: AcceptBlock : prev block 9391760af8fe350dae9b09d7145aa067a793a3cb473ba336c5d8a4af0b8cdbe2 is invalid, unable to add block db967a28602b79074e156b7c39534ba946685a5681b79c6462bda454ae700bca
2019-03-07 20:18:03 ERROR: ProcessNewBlock : AcceptBlock FAILED
2019-03-07 20:18:03 Misbehaving: 45.76.150.192:12700 (0 -> 100) BAN THRESHOLD EXCEEDED
2019-03-07 20:18:07 Misbehaving: [2a01:4f9:2a:1d90::2]:12700 (56 -> 57)

**Desktop (please complete the following information):**
 - OS: Windows 10 & Windows Server
 - Browser Chrome

**Additional context**
I notice the above 'BAN THRESHOLD EXCEEDED' - Could this be the problem?

**Comment by cevap** [comment] 2019-03-16 07:18
you might have tx in your wallet.dat which is not valid, restart your wallet with zapwallettxes=2 to recover transactions from blockchain and drop existing meta-data, you can do the same in QT by clicking 
![grafik](https://user-images.githubusercontent.com/24996551/54472146-01bf7f00-47c4-11e9-9743-a96c23270e08.png)

then resync.

**Comment by ioncoincore** [comment] 2019-04-20 22:30
@krumblez can this be closed or does the issue persist?

**Comment by cevap** [comment] 2019-08-01 10:16
@krumblez I assume the issue is fixed, I am closing this one, please reopen it if issue persists

**Closed as completed by cevap** 2019-08-01 10:16 UTC
Labels: Bug, Windows
